[package]
name = "pixelflow-ir"
version = "0.1.0"
edition = "2021"

[dependencies]
libm = "0.2"
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = ["std", "alloc"]
std = []
alloc = []

